#!/usr/bin/env python
#
# Based on:
# decodebin.py - Audio autopluging example using 'decodebin' element
# Copyright (C) 2006 Jason Gerard DeRose <jderose@jasonderose.org>
# Copyright (C) 2006 yokamaru https://gist.github.com/yokamaru/850506
# Copyright (C) 2013 Guillaume Pellerin

# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public
# License along with this library; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

import sys

from piplayer.player import PiPlayer

        
if __name__ == '__main__':
    if len(sys.argv) <= 1:
        print """ piplayer : a gstreamer based media sample player for the Raspberry Pi trigerred by GPIO or OSC callbacks 
  usage : sudo piplayer DIR
  example : sudo piplayer /path/to/dir/
    OSC : 
      port : 12345
      play address : /play/1
    GPIO :
      play channel : 22
      play method : PUD_DOWN between PIN 1 (3.3V Power) and PIN 15 (GPIO 22)
      stop channel : 24
      stop method : PUD_DOWN between PIN 1 (3.3V Power) and PIN 18 (GPIO 24)  
"""
    else:
        path = sys.argv[-1]
        player = PiPlayer(path)
        player.run()
    